### PR TITLE
Basic test for correct metadata

### PR DESCRIPTION
**Pull request by jamesgorman2**
Pending testing it on travis. I'm expecting this version to fail because of drafts, but not sure if the travis config is right. Run `npm i` to add `jest`, then `npm test` to test.

### CODE REVIEW

**Comment by jamesgorman2** [comment]
Looks like it's working (or at least failing as expected). Suggestions for more/changes to the tests welcome

**Comment by serra** [comment]
I like this a lot. Don't think I have time to go over it today in detail.
From first inspection, I thin the only thing that should be done is cleanup the test file a bit. Like remove some commented code. But I'm not well versed in Javascript and feel uncomfortable suggesting concrete changes.

I _love_ the build output with tiddler names and checkmarks, that's really helpful.

image

image

image

I can also imagine us (myself included after some JS freshup) to extend this with new tests.

**Comment by serra** [comment]
One thing that would help me is some examples of tiddlers with good and bad meta data.
E.g. encapsulate our business rules for meta data in a small library.
Test that library against our example dataset to test our rules.
Then use the rules library to test our wiki.

But we might not need that now, it feels a bit meta.

**Comment by serra** [comment]
This is great work @jamesgorman2 , I love it.

**Comment by serra** [comment]
And I suggest we add a simple makefile. That serves as good, usable documentation allowing us to clean up our readme.

**Comment by jamesgorman2** [comment]
I've set up `package.json` to do the build and updated the readme to be JS style.

**Review by serra — APPROVED** [review]

**Comment by jamesgorman2** [comment]
@zefram-cochrane I've added you to check:

* the deleted tiddlers
* new content on how to edit
* check the tests for metadata

**Pull request merged**
