### PR TITLE
Testing what happens when I scrag metadata 

### PR DESCRIPTION
**Pull request by zefram-cochrane**

### CODE REVIEW

**Comment by serra** [comment]
Great test @zefram-cochrane , fixing this is the purpose of #1 ,  which is the next issue we'll work on.

**Comment by serra** [comment]
@jamesgorman2 metadata are not required to compile/render a tiddler.
This pull request an attempt at scragging, but Tiddlywiki actually is fine with it.
Some reference on this can be found on https://tiddlywiki.com/static/TiddlerFiles.html

The following examples demonstrate my current understanding:

```
Now I am scragging the metadata!
No you are not.
First  paragraph before a newline is scanned for key-value pairs like the following line.
title: Dunbar Number
The rest is simply ignored.
The content after the first newline is interpreted as the content of the tiddler.

A social integrity limit from anthropology; ...
```

Will render as:

image

**Comment by serra** [comment]
a single or no newline at the top of tiddler causes the first paragraph to be interpreted as metadata. This _is_ a good scragging attempt:

```

A social integrity limit from anthropology; when any human group's size 
exceeds approximately 150 people, its participants can no longer ... 

```

image

**Comment by serra** [comment]
Two newlines works nicely:

image

**Comment by serra** [comment]
Not sure on how to detect scragging attempts. I was hoping the build would simply break, but in TiddlyWiki land we get away with quite a lot.

**Comment by jamesgorman2** [comment]
I'll have a look tomorrow. Might be able to detect some types of malformed
headers with a simple script, but I guess there will always be some that
can't be detected

**Pull request closed without merging**
